### ISSUE TITLE
Improved handling when instances can not be fully reconciled with order lines

### ISSUE THREAD

**Issue by thetis-apps** [thetis-apps/WebshipperIntegration#2]

**Comment by thetis-apps** [comment]
{
    "errorType": "Error",
    "errorMessage": "Could not fully reconcile instance with id: 68241107 (346508-NOBOX / 10)",
    "stack": [
        "Error: Could not fully reconcile instance with id: 68241107 (346508-NOBOX / 10)",
        "    at /var/task/src/handlers/handler.js:520:11",
        "    at Map.forEach (<anonymous>)",
        "    at patchOrder (/var/task/src/handlers/handler.js:473:14)",
        "    at Runtime.exports.handleShippingLabelRequest [as handler] (/var/task/src/handlers/handler.js:653:19)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

**Comment by thetis-apps** [comment]
Solved in 1.3.0
